name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: docker build . -t udm-mm-inputs

      - name: Test
        run: docker run -v $PWD/data:/data --env api_user=${{ secrets.NISMOD_API_USERNAME }} --env api_password=${{ secrets.NISMOD_API_PASSWORD }} --env area_codes='E08000021;' --env run_developed_ex_roads=false -t udm-mm-inputs
